### PR TITLE
fix(renovate): eslint v9 with flat config

### PR DESCRIPTION
**Pull request by felixvictor**
Some test cases fail but I cannot fix them. I have no knowledge in writing eslint rules :-)

### CODE REVIEW

**Comment by darraghoriordan** [comment]
hey thanks for doing this! much appreciated. I'm genuinely super busy at the moment so struggling to find time to code on this repo. I've enabled the build for you so if there are any errors you should be able to see them now.

I will take a proper look at any PRs soon. thanks again!

**Comment by felixvictor** [comment]
3 test cases are failing. I would like to correct these but I cannot. As I wrote earlier, I have no knowledge in writing eslint rules.

**Comment by darraghoriordan** [comment]
i fixed some failing tests but cant get your branch to pass tests. if you get a chance try merging from main.

**Comment by darraghoriordan** [comment]
i bumped main branch to ts eslint 8 too

**Pull request closed without merging**
