### PR TITLE
style: Fixed typo in code

### PR DESCRIPTION
**Pull request by nikelborm**
`initialize` instead of `initialise`

### CODE REVIEW

**Comment by Fishbowler** [comment]
Might be a typo. Might be a choice.

Initialise is valid English in non-US English speaking countries. Globalisation has somewhat closed the divide, but this and a bunch of other variant words live on.

I've got my eye on you, color/colour!

**Comment by nikelborm** [comment]
Idk, I pulled the repo to fix a real bug, but happened to see my grammar plugin in vs code swears

**Comment by darraghoriordan** [comment]
haha not a typo :D I'm Irish and we use "s" instead of z in most spelling. 

However most people would use "z" these days in code so thanks for the contribution

**Review by darraghoriordan — APPROVED** [review]

**Pull request merged**
